### ISSUE TITLE
Clicking/popping in the mixed signal

### ISSUE THREAD

**Issue by dejankosanovic** [mumble-voip/libmumble#20]
Hello everyone,

I am trying to build a simple VOIP app using your SDK. I managed to setup several clients and a server and connect those clients to the server, capture, encode and send the audio data as well as decode and render the received audio data. It works great when there are just two people in the call, but the issue arises when another one joins. For example, when two people start talking at the same time and the third one is listening - the mixed signal is audible meaning third person can understand the other two but there is some clicking/popping in the mixed signal. This is not an issue with the SDK but the mixed signal that is being played. I am just wondering if you encountered something like this during the development of the official Mumble/Murmur? I implemented very simple jitter buffer that just delays playing the audio for 200ms just to rule out this as a potential problem. 

Best regards,
Dejan

**Comment by davidebeatrici** [comment]
Hello,

Thank you very much for using our library!

The issue you describe is probably due to the use of a single `Opus::Decoder` object for all audio sources. There must be an instance for each source because Opus makes use of info acquired from precedent packets in order to deliver better quality and stability.

Best regards,
Davide

**Comment by dejankosanovic** [comment]
Hello Davide,

You were absolutely right, that was the issue I was having - I had just one decoder for all the incoming audio. I would have never found it so thanks a lot for the help, much appreciated!

Best regards,
Dejan

**Comment by davidebeatrici** [comment]
Hello Dejan,

I'm happy to be of help!

The upcoming documentation (no ETA yet) will contain a note about the necessity to use a separate `Opus::Decoder` instance for each audio source.

Best regards,
Davide
